//configuração do h2 para teste
#spring.application.name=easyinvest
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

//Conexão com o postgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/easyinvest
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

//valor inicial da Wallet
app.wallet.initial-balance=200000.00

//chave da api
alphavantage.api.key=3PBHVK1ZZE48NVC3

//config jwt
jwt.secret=easyinvest-secret-key-super-segura-123456